import React from "react";
import { afterEach, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { MemoryRouter } from "react-router-dom";
import { AxiosError } from "axios";
import { PatientsPage } from "../src/pages/patients/patients-page";
import { ToastProvider } from "../src/components/ui/toast";
import { patientService } from "../src/lib/services";
import type { Patient } from "../src/types";
vi.mock("@/hooks/use-permissions",()=>({usePermissions:()=>({can:()=>true})}));
let client: QueryClient;
afterEach(()=>{cleanup();client?.clear();vi.restoreAllMocks();});
const patient={id:"fictitious",full_name:"Fictitious saved patient",active:true,version:1} as Patient;
const preview={id:patient.id,full_name:patient.full_name,version:1,exam_count:2,exams_fingerprint:"a".repeat(64)};
const failure=(status:number)=>new AxiosError("failure","ERR_BAD_RESPONSE",undefined,undefined,
  {status,statusText:"Error",data:{detail:"Confira o cadastro e os exames."},headers:{},config:{} as never});
function setup() {
  const list=vi.spyOn(patientService,"list").mockResolvedValue({items:[patient],total:1});
  const view=vi.spyOn(patientService,"deletionPreview").mockResolvedValue(preview);
  client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});
  const invalidation=vi.spyOn(client,"invalidateQueries");
  const result=render(<MemoryRouter><QueryClientProvider client={client}><ToastProvider><PatientsPage /></ToastProvider></QueryClientProvider></MemoryRouter>);
  return {...result,list,view,invalidation};
}
it.each([409,404,403,503,"network"])("patient deletion %s keeps draft and requires reload and a new preview",async status=>{
  const remove=vi.spyOn(patientService,"remove").mockRejectedValueOnce(status==="network"?new Error("offline"):failure(Number(status))).mockResolvedValue();
  const {container,list,view,invalidation}=setup();
  fireEvent.click(await screen.findByRole("button",{name:"Editar",exact:true}));
  const notes=()=>container.querySelector('textarea[name="notes"]') as HTMLTextAreaElement;
  fireEvent.change(notes(),{target:{value:"Fictitious draft"}});
  fireEvent.click(screen.getByRole("button",{name:"Excluir",exact:true}));
  const confirm=await screen.findByRole("button",{name:"Confirmar exclusão",exact:true});
  expect(screen.getByText(/2 exame\(s\)/)).toBeTruthy();
  expect(screen.getByText("Cobranças e pagamentos já registrados permanecem.")).toBeTruthy();
  expect(remove).not.toHaveBeenCalled();
  fireEvent.click(confirm);
  const reload=await screen.findByRole("button",{name:"Recarregar lista para conferir"});
  expect(remove).toHaveBeenCalledWith(patient.id,1,preview.exams_fingerprint);
  expect(notes().value).toBe("Fictitious draft");
  expect((screen.getByRole("button",{name:"Excluir",exact:true}) as HTMLButtonElement).disabled).toBe(true);
  list.mockRejectedValueOnce(failure(503));fireEvent.click(reload);
  await waitFor(()=>expect(list).toHaveBeenCalledTimes(2));
  await waitFor(()=>expect((reload as HTMLButtonElement).disabled).toBe(false));
  const unavailable=screen.queryByRole("button",{name:"Excluir",exact:true}) as HTMLButtonElement | null;
  expect(unavailable === null || unavailable.disabled).toBe(true);
  list.mockResolvedValue({items:[{...patient,version:2}],total:1});
  view.mockResolvedValue({...preview,version:2,exam_count:3,exams_fingerprint:"b".repeat(64)});
  fireEvent.click(reload);
  await waitFor(()=>expect(screen.queryByRole("button",{name:"Recarregar lista para conferir"})).toBeNull());
  fireEvent.click(screen.getByRole("button",{name:"Excluir",exact:true}));
  await screen.findByText(/3 exame\(s\)/);
  expect(view).toHaveBeenLastCalledWith(patient.id,2);
  fireEvent.click(screen.getByRole("button",{name:"Confirmar exclusão",exact:true}));
  await waitFor(()=>expect(remove).toHaveBeenLastCalledWith(patient.id,2,"b".repeat(64)));
  await waitFor(()=>expect(invalidation).toHaveBeenCalledWith({queryKey:["financial"]}));
  expect(screen.queryByRole("button",{name:"Recarregar lista para conferir"})).toBeNull();
  expect(notes().value).toBe("Fictitious draft");
});
it("preview failure never deletes; successful preview can be cancelled",async()=>{
  const remove=vi.spyOn(patientService,"remove").mockResolvedValue();const {view}=setup();
  view.mockRejectedValueOnce(failure(403));
  fireEvent.click(await screen.findByRole("button",{name:"Excluir",exact:true}));
  fireEvent.click(await screen.findByRole("button",{name:"Recarregar lista para conferir"}));
  await waitFor(()=>expect(screen.queryByRole("button",{name:"Recarregar lista para conferir"})).toBeNull());
  fireEvent.click(screen.getByRole("button",{name:"Excluir",exact:true}));
  fireEvent.click(await screen.findByRole("button",{name:"Cancelar exclusão"}));
  expect(remove).not.toHaveBeenCalled();
});
it("exam cache invalidation withdraws a pending confirmation",async()=>{
  const remove=vi.spyOn(patientService,"remove").mockResolvedValue();setup();
  client.setQueryData(["exams",patient.id],[]);
  fireEvent.click(await screen.findByRole("button",{name:"Excluir",exact:true}));
  await screen.findByRole("button",{name:"Confirmar exclusão",exact:true});
  await client.invalidateQueries({queryKey:["exams",patient.id]});
  await screen.findByRole("button",{name:"Recarregar lista para conferir"});
  expect(screen.queryByRole("button",{name:"Confirmar exclusão",exact:true})).toBeNull();
  expect(remove).not.toHaveBeenCalled();
});
