Foreground yes
User clamav
DatabaseDirectory /var/lib/clamav
LocalSocket /tmp/clamd.sock
TCPSocket 3310
TCPAddr 0.0.0.0
LogTime yes
SelfCheck 60
ConcurrentDatabaseReload no
MaxThreads 2
MaxQueue 8
StreamMaxLength 1024M
MaxFileSize 1024M
MaxScanSize 1024M
MaxScanTime 30000
AlertExceedsMax yes
AlertEncrypted yes
