// Fictitious private schema only; never log credentials, requests or record contents.
const fs = require('node:fs'), path = require('node:path'), assert = require('node:assert/strict'), { randomUUID } = require('node:crypto');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
let stage = 'start';
process.on('unhandledRejection', () => { console.error('Financial refresh browser failed at stage: ' + stage); process.exit(1); });
(async () => {
 const credentials = JSON.parse(fs.readFileSync(0, 'utf8'));
 const browser = await chromium.launch({ channel: 'chrome', headless: true });
 const origin = 'https://localhost:18444';
 try {
  const context = () => browser.newContext({ timezoneId: 'America/Sao_Paulo', viewport: { width: 1440, height: 1100 } });
  const writer = await (await context()).newPage(), reader = await (await context()).newPage();
  const login = async (page, email) => {
   await page.goto(origin + '/login'); await page.locator('[name=email]').fill(email); await page.locator('[name=password]').fill(credentials.password);
   const response = page.waitForResponse(r => r.url().endsWith('/api/auth/login') && r.request().method() === 'POST');
   await page.getByRole('button', { name: 'Entrar', exact: true }).click(); const identity = await (await response).json();
   await page.getByRole('region', { name: 'Pacientes cadastrados', exact: true }).waitFor(); return identity;
  };
  stage = 'author login'; const author = await login(writer, credentials.email);
  const api = async (method, url, data) => {
   const result = await writer.evaluate(async ({ method, url, data, author }) => {
    const r = await fetch(url, { method, headers: { 'Content-Type': 'application/json', 'X-Session-ID': author.session_id, 'X-CSRF-Token': author.csrf_token }, body: data ? JSON.stringify(data) : undefined });
    return { status: r.status, body: r.status === 204 ? null : await r.json() };
   }, { method, url, data, author });
   assert.ok([200, 201, 204].includes(result.status), 'Fixture request rejected'); return result.body;
  };
  stage = 'fixtures';
  const patient = await api('POST', '/api/patients', { full_name: 'Fictitious Live Patient' });
  const dentist = await api('POST', '/api/dentists', { full_name: 'Fictitious Live Dentist' });
  const account = await api('POST', '/api/users', { name: 'Fictitious Financial Reader', email: 'financial-reader@example.com', password: credentials.password, role: 'reception' });
  let matrix = (await api('GET', '/api/permissions')).items.find(p => p.role === 'reception');
  for (const name of ['financial', 'patients', 'dentists', 'appointments', 'dashboard']) matrix.permissions[name] = { view: true, create: true, update: true, delete: true };
  const saveMatrix = async () => { matrix = await api('PUT', '/api/permissions/reception', { version: matrix.version, permissions: matrix.permissions }); };
  await saveMatrix();
  const day = new Date().toISOString().slice(0, 10);
  const payload = { entry_type: 'income', description: 'Fictitious Live Charge', amount_cents: 12000, due_date: day, patient_id: patient.id, dentist_id: dentist.id };
  let entry = await api('POST', '/api/financial', payload);
  stage = 'reader login'; const receiver = await login(reader, account.email); assert.notEqual(receiver.session_id, author.session_id);
  await reader.goto(origin + '/financial');
  const list = reader.getByRole('region', { name: 'Lançamentos financeiros', exact: true });
  const totals = reader.getByRole('region', { name: 'Resumo financeiro', exact: true });
  const row = name => list.getByRole('row').filter({ hasText: name });
  const search = reader.getByPlaceholder('Buscar por descricao, paciente ou dentista');
  const refreshList = () => list.getByRole('button', { name: 'Atualizar lançamentos financeiros', exact: true });
  const refreshSummary = () => totals.getByRole('button', { name: 'Atualizar resumo financeiro', exact: true });
  await row(entry.description).waitFor();
  await search.fill('Fictitious Live');
  await reader.getByLabel('Vencimento inicial', { exact: true }).fill(day); await reader.getByLabel('Vencimento final', { exact: true }).fill(day);
  await reader.locator('select[aria-label="Filtrar por tipo"]').selectOption('income', { force: true });
  await reader.locator('select[aria-label="Filtrar por status"]').selectOption('pending', { force: true });
  await reader.locator('select[aria-label="Filtrar por paciente"]').selectOption(patient.id, { force: true });
  await reader.locator('select[aria-label="Filtrar por dentista"]').selectOption(dentist.id, { force: true });
  await row(entry.description).waitFor(); await reader.waitForLoadState('networkidle');
  let listReads = 0, summaryReads = 0, writes = 0;
  reader.on('request', r => {
   const url = new URL(r.url()); if (r.method() === 'GET' && url.pathname === '/api/financial') listReads++;
   if (r.method() === 'GET' && url.pathname === '/api/financial/summary') summaryReads++;
   if (['POST', 'PUT', 'DELETE'].includes(r.method()) && url.pathname.startsWith('/api/')) writes++;
  });
  stage = 'remote edit with draft'; await row(entry.description).getByRole('button', { name: 'Editar', exact: true }).click();
  await reader.locator('[name=amount]').fill('321.09'); await reader.locator('[name=notes]').fill('Fictitious draft');
  const oldVersion = entry.version; const observedAt = Date.now();
  entry = await api('PUT', '/api/financial/' + entry.id, { version: entry.version, description: 'Fictitious Live Remote', amount_cents: 23456 });
  await row(entry.description).waitFor({ timeout: 25000 }); const latency = Date.now() - observedAt;
  assert.equal(await reader.locator('[name=notes]').inputValue(), 'Fictitious draft');
  assert.equal(await reader.locator('[name=description]').inputValue(), payload.description);
  assert.equal(await reader.locator('[name=amount]').inputValue(), '321.09'); assert.equal(writes, 0);
  assert.equal(await search.inputValue(), 'Fictitious Live'); assert.equal(await reader.getByLabel('Vencimento inicial', { exact: true }).inputValue(), day);
  for (const [label, value] of [['tipo', 'income'], ['status', 'pending'], ['paciente', patient.id], ['dentista', dentist.id]]) assert.equal(await reader.locator('select[aria-label="Filtrar por ' + label + '"]').inputValue(), value);
  stage = 'old edit rejected';
  const edited = reader.waitForResponse(r => r.request().method() === 'PUT' && r.url().endsWith('/api/financial/' + entry.id));
  await reader.getByRole('button', { name: 'Salvar', exact: true }).click(); const rejected = await edited;
  assert.equal(rejected.status(), 409); assert.equal(rejected.request().postDataJSON().version, oldVersion);
  await reader.getByRole('button', { name: 'Descartar rascunho e carregar atual', exact: true }).waitFor();
  await reader.getByRole('button', { name: 'Cancelar', exact: true }).click();
  stage = 'remote payment with action open'; await row(entry.description).getByRole('button', { name: 'Baixar', exact: true }).click();
  const paymentVersion = entry.version;
  await api('POST', '/api/financial/' + entry.id + '/mark-paid', { version: entry.version, idempotency_key: randomUUID(), paid_at: null, payment_method: 'pix' });
  await row(entry.description).waitFor({ state: 'hidden', timeout: 25000 });
  await totals.getByText(/Recebido:.*234,56/).waitFor({ timeout: 25000 });
  assert.equal(writes, 1); await reader.getByText('Estado de referência da ação: Pendente.', { exact: true }).waitFor();
  const settlement = reader.waitForResponse(r => r.request().method() === 'POST' && r.url().endsWith('/mark-paid'));
  await reader.getByRole('button', { name: 'Confirmar baixa integral', exact: true }).click(); const conflict = await settlement;
  assert.equal(conflict.status(), 409); assert.equal(conflict.request().postDataJSON().version, paymentVersion);
  await reader.getByRole('button', { name: 'Fechar', exact: true }).click();
  await reader.locator('select[aria-label="Filtrar por status"]').selectOption('', { force: true }); await row(entry.description).waitFor();
  stage = 'independent list failure'; const listPattern = /\/api\/financial(?:\?.*)?$/;
  const unavailable = route => route.fulfill({ status: 503, contentType: 'application/json', body: '{"detail":"Fictitious unavailable"}' });
  await reader.route(listPattern, unavailable); await refreshList().click(); await list.getByRole('alert').waitFor();
  await row(entry.description).waitFor();
  await api('POST', '/api/financial', { ...payload, entry_type: 'expense', description: 'Fictitious expense outside list', amount_cents: 5000 });
  await totals.getByText('Lancamentos: 2', { exact: true }).waitFor({ timeout: 25000 });
  await search.fill('No matching fictitious record'); await list.getByText('Não foi possível carregar lançamentos financeiros.', { exact: true }).waitFor();
  assert.equal(await list.getByText(entry.description, { exact: true }).count(), 0); assert.equal(await list.getByText(/Nenhum lancamento/).count(), 0);
  await reader.unroute(listPattern); await refreshList().click(); await list.getByText(/Nenhum lancamento/).waitFor();
  await search.fill('Fictitious Live'); await row(entry.description).waitFor();
  stage = 'independent summary failure'; const summaryPattern = /\/api\/financial\/summary(?:\?.*)?$/;
  await reader.route(summaryPattern, unavailable); await refreshSummary().click(); await totals.getByRole('alert').waitFor();
  const third = await api('POST', '/api/financial', { ...payload, description: 'Fictitious Live New', amount_cents: 9900 });
  await row(third.description).waitFor({ timeout: 25000 }); await totals.getByText('Lancamentos: 2', { exact: true }).waitFor();
  for (const dark of [false, true]) {
   await reader.evaluate(dark => document.documentElement.classList.toggle('dark', dark), dark);
   await reader.screenshot({ path: path.resolve(__dirname, '../.data/homolog/financial-refresh-' + (dark ? 'dark' : 'light') + '.png'), fullPage: true, animations: 'disabled' });
  }
  await reader.getByLabel('Vencimento final', { exact: true }).fill('2031-01-01');
  await totals.getByText('Não foi possível carregar resumo financeiro.', { exact: true }).waitFor();
  assert.equal(await totals.getByText(/R\$/).count(), 0);
  await reader.unroute(summaryPattern); await refreshSummary().click(); await totals.getByText('Lancamentos: 3', { exact: true }).waitFor();
  stage = 'remote deletion'; await api('DELETE', '/api/financial/' + third.id + '?version=' + third.version);
  await row(third.description).waitFor({ state: 'hidden', timeout: 25000 });
  stage = 'hidden pause';
  await reader.evaluate(() => { Object.defineProperty(document, 'visibilityState', { configurable: true, get: () => 'hidden' }); document.dispatchEvent(new Event('visibilitychange')); });
  await reader.waitForLoadState('networkidle'); const before = [listReads, summaryReads]; await reader.waitForTimeout(17000);
  assert.deepEqual([listReads, summaryReads], before);
  await reader.evaluate(() => { Object.defineProperty(document, 'visibilityState', { configurable: true, get: () => 'visible' }); document.dispatchEvent(new Event('visibilitychange')); window.dispatchEvent(new Event('focus')); });
  await totals.getByText('Lancamentos: 2', { exact: true }).waitFor({ timeout: 25000 }); assert.equal(writes, 2);
  stage = 'read revocation'; matrix.permissions.financial.view = false; await saveMatrix();
  await reader.getByText(/Sem permissão para acessar esta página\.|Seu acesso ao financeiro foi encerrado\./).waitFor({ timeout: 25000 });
  assert.equal(await reader.getByRole('region', { name: 'Resumo financeiro', exact: true }).count(), 0);
  assert.equal(await reader.evaluate(async id => (await fetch('/api/financial', { headers: { 'X-Session-ID': id } })).status, receiver.session_id), 403);
  console.log('PASS: independent sessions; remote edit observed in ' + latency + 'ms; ' + listReads + ' list GETs/' + summaryReads + ' summary GETs in full scenario; filters/draft/version preserved; stale payment rejected; create/delete; independent failures/recovery; hidden pause; read revocation/HTTP 403; only two explicit writes.');
 } finally { await browser.close(); }
})().catch(() => { console.error('Financial refresh browser failed at stage: ' + stage); process.exitCode = 1; });
