// Private fictitious fixtures only. Never emit credentials, headers or bodies.
const fs = require('node:fs'), path = require('node:path'), assert = require('node:assert/strict');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
let stage = 'start';
process.on('unhandledRejection', () => { console.error('User refresh browser failed at stage: ' + stage); process.exit(1); });
(async () => {
 const credentials = JSON.parse(fs.readFileSync(0, 'utf8'));
 const browser = await chromium.launch({ channel: 'chrome', headless: true });
 const origin = 'https://localhost:18444';
 try {
  const context = () => browser.newContext({ timezoneId: 'America/Sao_Paulo', viewport: { width: 1440, height: 1100 } });
  const writer = await (await context()).newPage(), reader = await (await context()).newPage();
  const login = async (page, email) => {
   await page.goto(origin + '/login'); await page.locator('[name=email]').fill(email); await page.locator('[name=password]').fill(credentials.password);
   const response = page.waitForResponse(r => r.url().endsWith('/api/auth/login') && r.request().method() === 'POST');
   await page.getByRole('button', { name: 'Entrar', exact: true }).click(); const identity = await (await response).json();
   await page.getByRole('region', { name: 'Pacientes cadastrados', exact: true }).waitFor(); return identity;
  };
  stage = 'author login'; const author = await login(writer, credentials.email);
  const api = async (method, url, data) => {
   const result = await writer.evaluate(async ({ method, url, data, author }) => {
    const r = await fetch(url, { method, headers: { 'Content-Type': 'application/json', 'X-Session-ID': author.session_id, 'X-CSRF-Token': author.csrf_token }, body: data ? JSON.stringify(data) : undefined });
    return { status: r.status, body: r.status === 204 ? null : await r.json() };
   }, { method, url, data, author });
   assert.ok([200, 201, 204].includes(result.status), 'Fixture request rejected'); return result.body;
  };
  stage = 'fixtures';
  let account = await api('POST', '/api/users', { name: 'Fictitious List Operator', email: 'user-live-operator@example.com', password: credentials.password, role: 'reception' });
  let matrix = (await api('GET', '/api/permissions')).items.find(p => p.role === 'reception');
  matrix.permissions.users = { view: true, create: true, update: true, delete: true };
  const saveMatrix = async () => { matrix = await api('PUT', '/api/permissions/reception', { version: matrix.version, permissions: matrix.permissions }); }; await saveMatrix();
  let item = await api('POST', '/api/users', { name: 'Fictitious Live User', email: 'user-live-target@example.com', password: credentials.password, role: 'reception' });
  const endpoint = '/api/users/' + item.id;
  stage = 'reader login'; const receiver = await login(reader, account.email); assert.notEqual(receiver.session_id, author.session_id);
  let reads = 0, refs = 0, writes = 0;
  reader.on('request', r => { const p = new URL(r.url()).pathname;
   if (r.method() === 'GET' && p === '/api/users') reads++;
   if (r.method() === 'GET' && p === '/api/dentists') refs++;
   if (['POST', 'PUT', 'DELETE'].includes(r.method()) && p.startsWith('/api/users')) writes++;
  });
  const row = name => reader.getByRole('row').filter({ hasText: name });
  const button = name => reader.getByRole('button', { name, exact: true });
  const refresh = () => button('Atualizar usuários');
  const submit = async (method, url, name, status, version) => {
   const pending = reader.waitForResponse(r => r.url().includes(url) && r.request().method() === method);
   await button(name).click(); const r = await pending; assert.equal(r.status(), status);
   if (version) assert.equal(r.request().postDataJSON().version, version);
   return r;
  };
  stage = 'initial'; await reader.goto(origin + '/users'); await row(item.name).waitFor();
  const search = reader.getByPlaceholder('Buscar por nome ou e-mail'); await search.fill('Fictitious Live'); await reader.waitForLoadState('networkidle'); const refsBefore = refs;
  stage = 'remote edit with draft'; await row(item.name).getByRole('button', { name: 'Editar', exact: true }).click(); await reader.locator('[name=name]').fill('Fictitious retained draft');
  const oldVersion = item.version, observedAt = Date.now();
  item = await api('PUT', endpoint, { version: item.version, name: 'Fictitious Live Remote User', is_active: false });
  await row(item.name).waitFor({ timeout: 25000 }); const latency = Date.now() - observedAt;
  await row(item.name).getByRole('cell', { name: 'Não', exact: true }).waitFor();
  assert.equal(await search.inputValue(), 'Fictitious Live'); assert.equal(await reader.locator('[name=name]').inputValue(), 'Fictitious retained draft');
  stage = 'captured edit conflict'; await submit('PUT', endpoint, 'Salvar', 409, oldVersion);
  await button('Descartar e carregar atual').waitFor(); assert.equal(await button('Salvar').isDisabled(), true); await button('Cancelar').click();
  stage = 'captured password conflict'; await row(item.name).getByRole('button', { name: 'Senha', exact: true }).click();
  await reader.locator('[name=new_password]').fill(credentials.password); await reader.locator('[name=confirm_password]').fill(credentials.password);
  const passwordVersion = item.version; item = await api('PUT', endpoint, { version: item.version, name: 'Fictitious Live Password Target' });
  await row(item.name).waitFor({ timeout: 25000 }); assert.ok(await reader.locator('[name=new_password]').inputValue() === credentials.password);
  await submit('POST', endpoint + '/set-password', 'Salvar senha', 409, passwordVersion);
  await button('Descartar e carregar atual').waitFor(); assert.equal(await reader.locator('[name=new_password]').inputValue(), ''); assert.equal(await reader.locator('[name=confirm_password]').inputValue(), '');
  await reader.waitForTimeout(17000); assert.equal(await button('Salvar senha').isDisabled(), true); await button('Cancelar').click();
  stage = 'captured deletion conflict'; await row(item.name).getByRole('button', { name: 'Excluir', exact: true }).click();
  const deleteVersion = item.version; item = await api('PUT', endpoint, { version: item.version, name: 'Fictitious Live Delete Target' });
  await row(item.name).waitFor({ timeout: 25000 });
  const rejected = await submit('DELETE', endpoint, 'Confirmar exclusão', 409); assert.ok(rejected.url().endsWith('?version=' + deleteVersion));
  await button('Descartar e carregar atual').waitFor(); await reader.waitForTimeout(17000); assert.equal(await button('Confirmar exclusão').isDisabled(), true); await button('Cancelar').click();
  stage = 'failure and recovery'; const pattern = /\/api\/users(?:\?.*)?$/;
  await reader.route(pattern, route => route.fulfill({ status: 503, contentType: 'application/json', body: '{"detail":"Fictitious unavailable"}' }));
  await refresh().click(); await reader.getByText(/Os dados exibidos podem estar desatualizados/).waitFor(); await row(item.name).waitFor();
  for (const dark of [false, true]) { await reader.evaluate(dark => document.documentElement.classList.toggle('dark', dark), dark);
   await reader.screenshot({ path: path.resolve(__dirname, '../.data/homolog/user-refresh-' + (dark ? 'dark' : 'light') + '.png'), fullPage: true, animations: 'disabled' }); }
  await search.fill('Fictitious unmatched'); await reader.getByText('Não foi possível carregar usuários.', { exact: true }).waitFor(); assert.equal(await row(item.name).count(), 0);
  assert.equal(await reader.getByText('Nenhum usuário encontrado.').count(), 0); await reader.unroute(pattern); await refresh().click(); await reader.getByText('Nenhum usuário encontrado.').waitFor();
  await search.fill('Fictitious Live'); await row(item.name).waitFor();
  stage = 'remote creation/deletion'; const created = await api('POST', '/api/users', { name: 'Fictitious Live Created User', email: 'user-live-created@example.com', password: credentials.password, role: 'reception' });
  await row(created.name).waitFor({ timeout: 25000 }); await row(created.name).getByRole('button', { name: 'Editar', exact: true }).click(); await reader.locator('[name=name]').fill('Fictitious deleted draft');
  await api('DELETE', '/api/users/' + created.id + '?version=' + created.version); await row(created.name).waitFor({ state: 'hidden', timeout: 25000 });
  assert.equal(await reader.locator('[name=name]').inputValue(), 'Fictitious deleted draft');
  await submit('PUT', '/api/users/' + created.id, 'Salvar', 404); await reader.locator('[name=name]').waitFor({ state: 'hidden' });
  stage = 'hidden pause'; await reader.evaluate(() => { Object.defineProperty(document, 'visibilityState', { configurable: true, get: () => 'hidden' }); document.dispatchEvent(new Event('visibilitychange')); });
  await reader.waitForLoadState('networkidle'); const before = reads; await reader.waitForTimeout(17000); assert.equal(reads, before);
  await reader.evaluate(() => { Object.defineProperty(document, 'visibilityState', { configurable: true, get: () => 'visible' }); document.dispatchEvent(new Event('visibilitychange')); window.dispatchEvent(new Event('focus')); });
  stage = 'read revocation with password draft'; await row(item.name).getByRole('button', { name: 'Senha', exact: true }).click(); await reader.locator('[name=new_password]').fill(credentials.password);
  matrix.permissions.users.view = false; await saveMatrix();
  await reader.getByText(/Sem permissão para acessar esta página\.|Seu acesso à administração/).waitFor({ timeout: 25000 }); assert.equal(await reader.locator('[name=new_password]').count(), 0);
  assert.equal(await reader.evaluate(async id => (await fetch('/api/users', { headers: { 'X-Session-ID': id } })).status, receiver.session_id), 403);
  assert.equal(refs, refsBefore); assert.equal(writes, 4);
  stage = 'own session revoked'; matrix.permissions.users.view = true; await saveMatrix(); await reader.goto(origin + '/users'); await row(item.name).waitFor();
  await row(item.name).getByRole('button', { name: 'Senha', exact: true }).click(); await reader.locator('[name=new_password]').fill(credentials.password);
  account = await api('PUT', '/api/users/' + account.id, { version: account.version, is_active: false });
  await reader.waitForURL('**/login', { timeout: 25000 }); assert.equal(await reader.locator('[name=new_password]').count(), 0); assert.equal(await row(item.name).count(), 0);
  await reader.goto(origin + '/users'); await reader.waitForURL('**/login'); assert.equal(await row(item.name).count(), 0);
  console.log('PASS: independent sessions; remote user edit in ' + latency + 'ms; search/drafts/versions preserved; password/deletion conflicts require review; secrets cleared; create/delete/404; failures/recovery; hidden pause; read revocation/403; own session revoked and cannot reopen; four explicit writes only.');
 } finally { await browser.close(); }
})().catch(() => { console.error('User refresh browser failed at stage: ' + stage); process.exitCode = 1; });
