const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
let stage='start';
process.on('unhandledRejection',()=>{console.error('Permissions browser failed at stage: '+stage);process.exit(1);});
(async()=>{
 const credentials=JSON.parse(fs.readFileSync(0,'utf8'));
 const browser=await chromium.launch({channel:'chrome',headless:true});
 try {
  const context=await browser.newContext({ignoreHTTPSErrors:false,viewport:{width:1440,height:1000}});
  const other=await browser.newContext({ignoreHTTPSErrors:false,viewport:{width:1440,height:1000}});
  const first=await context.newPage(),second=await other.newPage();
  stage='login';await first.goto('https://localhost:18444/login');
  await first.locator('[name=email]').fill(credentials.email);await first.locator('[name=password]').fill(credentials.password);
  const pending=first.waitForResponse(r=>r.url().endsWith('/api/auth/login')&&r.request().method()==='POST');
  await first.getByRole('button',{name:'Entrar',exact:true}).click();
  const logged=await(await pending).json();await first.getByText('Pacientes cadastrados',{exact:true}).waitFor();
  await second.goto('https://localhost:18444/login');
  await second.locator('[name=email]').fill(credentials.email);await second.locator('[name=password]').fill(credentials.password);
  const otherLogin=second.waitForResponse(r=>r.url().endsWith('/api/auth/login')&&r.request().method()==='POST');
  await second.getByRole('button',{name:'Entrar',exact:true}).click();const receiver=await(await otherLogin).json();
  assert.notEqual(receiver.session_id,logged.session_id);await second.getByText('Pacientes cadastrados',{exact:true}).waitFor();
  let reads=0,writes=0;
  second.on('request',r=>{if(new URL(r.url()).pathname==='/api/permissions'&&r.method()==='GET')reads++;
   if(new URL(r.url()).pathname.startsWith('/api/permissions/')&&r.method()==='PUT')writes++;});
  const headers={'Content-Type':'application/json','X-Session-ID':logged.session_id,'X-CSRF-Token':logged.csrf_token};
  const api=(method,url,data)=>first.evaluate(async({method,url,data,headers})=>{
   const response=await fetch(url,{method,headers,body:data?JSON.stringify(data):undefined});
   return {status:response.status,body:await response.json()};
  },{method,url,data,headers});
  const open=(page,name)=>page.getByRole('button',{name:new RegExp(name)}).click();
  const field=(page,role,action)=>page.getByRole('checkbox',{name:`${role}: Pacientes — ${action}`,exact:true});
  const save=async(page,role)=>{
   const result=page.waitForResponse(r=>r.url().endsWith('/api/permissions/'+role)&&r.request().method()==='PUT');
   await page.getByRole('button',{name:'Salvar Permissões',exact:true}).click();return result;
  };
  stage='load old forms';
  for(const page of [first,second]) {await page.goto('https://localhost:18444/permissions');await page.getByText('Permissões por Perfil',{exact:true}).waitFor();}
  await open(first,'Coordenador');await field(first,'Coordenador','Ver').uncheck();
  await open(first,'Recepcao');await open(second,'Coordenador');await field(second,'Coordenador','Ver').uncheck();await open(second,'Recepcao');
  const observedAt=Date.now();stage='save one profile';await field(first,'Recepcao','Criar').uncheck();assert.equal((await save(first,'reception')).status(),200);
  await open(first,'Coordenador');assert.equal(await field(first,'Coordenador','Ver').isChecked(),false);
  stage='automatic remote observation';
  await second.getByText(/Recepcao: há uma versão mais recente/).waitFor({timeout:25000});const latency=Date.now()-observedAt;
  assert.equal(await field(second,'Recepcao','Criar').isChecked(),true);assert.equal(writes,0);
  stage='stale second form';await field(second,'Recepcao','Ver').uncheck();
  const conflict=await save(second,'reception');assert.equal(conflict.status(),409);assert.equal((await conflict.json()).code,'stale_version');
  const reload=second.getByRole('button',{name:'Descartar rascunho e carregar atual',exact:true});await reload.waitFor();
  assert.equal(await second.getByRole('button',{name:'Salvar Permissões',exact:true}).isDisabled(),true);
  stage='failed reload keeps draft';
  await second.route('**/api/permissions',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'Fictitious unavailable'})}));
  const failed=second.waitForResponse(r=>r.url().endsWith('/api/permissions')&&r.status()===503);
  await reload.click();await failed;
  await second.getByText(/serviço está temporariamente indisponível/).waitFor();
  assert.equal(await field(second,'Recepcao','Ver').isChecked(),false);
  assert.equal(await second.getByRole('button',{name:'Salvar Permissões',exact:true}).isDisabled(),true);
  await second.screenshot({path:path.resolve(__dirname,'../.data/homolog/permission-version-conflict.png'),fullPage:true});
  for(const dark of [false,true]) {await second.evaluate(dark=>document.documentElement.classList.toggle('dark',dark),dark);
   await second.screenshot({path:path.resolve(__dirname,'../.data/homolog/permission-refresh-'+(dark?'dark':'light')+'.png'),fullPage:true});}
  stage='explicit reload and review';await second.unroute('**/api/permissions');
  const loaded=second.waitForResponse(r=>r.url().endsWith('/api/permissions')&&r.status()===200);
  await reload.click();await loaded;await second.getByText('Permissões atuais carregadas. Revise antes de salvar.',{exact:true}).waitFor();
  assert.equal(await field(second,'Recepcao','Ver').isChecked(),true);assert.equal(await field(second,'Recepcao','Criar').isChecked(),false);
  assert.equal((await api('GET','/api/permissions')).body.items.find(x=>x.role==='reception').version,2);
  await open(second,'Coordenador');assert.equal(await field(second,'Coordenador','Ver').isChecked(),false);await open(second,'Recepcao');
  await field(second,'Recepcao','Ver').uncheck();assert.equal((await save(second,'reception')).status(),200);
  stage='independent coordinator draft';assert.equal(await field(first,'Coordenador','Ver').isChecked(),false);
  assert.equal((await save(first,'coordinator')).status(),200);
  const result=(await api('GET','/api/permissions')).body.items;
  assert.equal(result.find(x=>x.role==='reception').version,3);assert.equal(result.find(x=>x.role==='coordinator').version,2);
  await first.screenshot({path:path.resolve(__dirname,'../.data/homolog/permission-version-independent.png'),fullPage:true});
  stage='stale read and recovery';
  const pattern='**/api/permissions';await second.route(pattern,route=>route.fulfill({status:503,contentType:'application/json',body:'{"detail":"Fictitious unavailable"}'}));
  await second.getByRole('button',{name:'Atualizar permissões',exact:true}).click();await second.getByText(/Os dados exibidos podem estar desatualizados/).waitFor();
  assert.equal(await field(second,'Recepcao','Ver').isChecked(),false);
  await second.unroute(pattern);await second.getByRole('button',{name:'Atualizar permissões',exact:true}).click();
  await second.getByText('Atualização automática ativa.',{exact:true}).waitFor();
  stage='hidden pause';await second.evaluate(()=>{Object.defineProperty(document,'visibilityState',{configurable:true,get:()=> 'hidden'});document.dispatchEvent(new Event('visibilitychange'));});
  await second.waitForLoadState('networkidle');const before=reads;await second.waitForTimeout(17000);assert.equal(reads,before);
  await second.evaluate(()=>{Object.defineProperty(document,'visibilityState',{configurable:true,get:()=> 'visible'});document.dispatchEvent(new Event('visibilitychange'));window.dispatchEvent(new Event('focus'));});
  assert.equal(writes,2);
  stage='administrative denial';await second.route(pattern,route=>route.fulfill({status:403,contentType:'application/json',body:'{"detail":"Fictitious denied"}'}));
  await second.getByRole('button',{name:'Atualizar permissões',exact:true}).click();await second.getByText(/Seu acesso à administração de permissões/).waitFor();assert.equal(await second.getByRole('checkbox').count(),0);
  await second.unroute(pattern);
  stage='revoked own session';await second.goto('https://localhost:18444/permissions');await open(second,'Recepcao');
  assert.equal(await second.evaluate(async({session,csrf})=>(await fetch('/api/auth/logout',{method:'POST',headers:{'X-Session-ID':session,'X-CSRF-Token':csrf}})).status,{session:receiver.session_id,csrf:receiver.csrf_token}),200);
  await second.waitForURL('**/login',{timeout:25000});assert.equal(await second.getByRole('checkbox').count(),0);
  assert.equal((await api('GET','/api/permissions')).status,200);
  console.log('PASS: independent Chrome sessions; remote permissions observed in '+latency+'ms; drafts/versions preserved; explicit reload changes only selected role; real 409; failed reload and stale read/recovery; hidden pause; administrative denial; real session revocation; two explicit writes only.');
 } finally {await browser.close();}
})().catch(()=>{console.error('Permissions browser failed at stage: '+stage);process.exitCode=1;});
